"""Deluge integration constants."""

DOMAIN = "deluge"
DEFAULT_PORT = 58846
UPLOAD_RATE = "upload_rate"
DOWNLOAD_RATE = "download_rate"
DHT_UPLOAD_RATE = "dht_upload_rate"
DHT_DOWNLOAD_RATE = "dht_download_rate"
CORE_GET_SESSION_STATUS = "core.get_session_status"
CORE_GET_SESSION_STATE = "core.get_session_state"
CORE_GET_TORRENTS_STATUS = "core.get_torrents_status"
CORE_RESUME_TORRENT = "core.resume_torrent"
CORE_PAUSE_TORRENT = "core.pause_torrent"
CURRENT_STATUS = "current_status"
DOWNLOAD_SPEED = "download_speed"
UPLOAD_SPEED = "upload_speed"
SENSORS_COORDINATOR_DATA_NAME = "deluge-session-status-sensors"
STATE_UP_DOWN = "Up/Down"
STATE_SEEDING = "Seeding"
STATE_DOWNLOADING = "Downloading"
USERNAME_ERROR_TEXT = "Username does not exist"
PASSWORD_ERROR_TEXT = "Password does not match"
PAUSED = "paused"
